local SkillsIncompatibility = {

    --[[["Airborne"] = {
        "Opening Shot",
        "Rapid Fire Up"
    },]]--
    ["Artillery"] = {
        "Blast Functionality",
        "Charge Up",
        "Exhaust Functionality",
        "Horn Maestro",
        "Para Functionality",
        "Poison Functionality",
        "Sleep Functionality"
    },
    ["Ballistics"] = {
        "Bludgeoner",
        "Charge Up",
        "Critical Draw",
        "Handicraft",
        "Horn Maestro",
        --"Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Rapid Morph",
        "Razor Sharp",
        "Speed Sharpening"
    },
    ["Blast Functionality"] = {
        "Artillery",
        "Bludgeoner",
        "Charge Up",
        "Critical Draw",
        "Guard",
        "Guard Up",
        "Handicraft",
        "Horn Maestro",
        "Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Offensive Guard",
        "Opening Shot",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Rapid Fire Up",
        "Rapid Morph",
        "Razor Sharp",
        "Speed Sharpening"
    },
    ["Bludgeoner"] = {
        "Ballistics",
        "Blast Functionality",
        "Exhaust Functionality",
        "Normal Shots",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Charge Master"] = {
        --"Horn Maestro",
        --"Opening Shot",
        "Rapid Fire Up"
    },
    ["Charge Up"] = {
        "Artillery",
        "Ballistics",
        "Blast Functionality",
        "Exhaust Functionality",
        "Guard",
        "Guard Up",
        "Horn Maestro",
        "Load Shells",
        "Normal Shots",
        "Offensive Guard",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Power Prolonger",
        "Rapid Fire Up",
        "Rapid Morph",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Critical Draw"] = {
        "Ballistics",
        "Blast Functionality",
        "Exhaust Functionality",
        "Normal Shots",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Exhaust Functionality"] = {
        "Artillery",
        "Bludgeoner",
        "Charge Up",
        "Critical Draw",
        "Guard",
        "Guard Up",
        "Handicraft",
        "Horn Maestro",
        "Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Offensive Guard",
        "Opening Shot",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Rapid Fire Up",
        "Rapid Morph",
        "Razor Sharp",
        "Speed Sharpening"
    },
    --[[["Focus"] = {
        "Horn Maestro"
    },]]--
    ["Guard"] = {
        "Blast Functionality",
        "Charge Up",
        "Exhaust Functionality",
        "Horn Maestro",
        "Para Functionality",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality"
    },
    ["Guard Up"] = {
        "Blast Functionality",
        "Charge Up",
        "Exhaust Functionality",
        "Horn Maestro",
        "Para Functionality",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality"
    },
    ["Handicraft"] = {
        "Ballistics",
        "Blast Functionality",
        "Exhaust Functionality",
        "Normal Shots",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Horn Maestro"] = {
        "Artillery",
        "Ballistics",
        "Blast Functionality",
        --"Charge Master",
        "Charge Up",
        "Exhaust Functionality",
        --"Focus",
        "Guard",
        "Guard Up",
        "Load Shells",
        "Normal Shots",
        "Offensive Guard",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Power Prolonger",
        "Rapid Fire Up",
        "Rapid Morph",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Load Shells"] = {
        --"Ballistics",
        "Blast Functionality",
        "Charge Up",
        "Exhaust Functionality",
        "Horn Maestro",
        --"Normal Shots",
        --"Opening Shot",
        --"Para Functionality",
        --"Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        --"Special Ammo Boost",
        --"Spread/Power Shots",
        --"Tetrad Shot"
    },
    ["Master's Touch"] = {
        "Ballistics",
        "Blast Functionality",
        "Exhaust Functionality",
        "Normal Shots",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Mind's Eye"] = {
        "Ballistics",
        "Blast Functionality",
        "Exhaust Functionality",
        "Normal Shots",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Normal Shots"] = {
        "Bludgeoner",
        "Charge Up",
        "Critical Draw",
        "Handicraft",
        "Horn Maestro",
        --"Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Rapid Morph",
        "Razor Sharp",
        "Speed Sharpening"
    },
    ["Offensive Guard"] = {
        "Blast Functionality",
        "Charge Up",
        "Exhaust Functionality",
        "Horn Maestro",
        "Para Functionality",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality"
    },
    ["Opening Shot"] = {
        --"Airborne",
        "Blast Functionality",
        "Bludgeoner",
        --"Charge Master",
        "Critical Draw",
        "Exhaust Functionality",
        "Handicraft",
        "Horn Maestro",
        --"Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Para Functionality",
        "Poison Functionality",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Razor Sharp",
        "Rapid Morph",
        "Sleep Functionality",
        "Speed Sharpening"
    },
    ["Para Functionality"] = {
        "Artillery",
        "Bludgeoner",
        "Charge Up",
        "Critical Draw",
        "Guard",
        "Guard Up",
        "Handicraft",
        "Horn Maestro",
        "Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Offensive Guard",
        "Opening Shot",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Rapid Fire Up",
        "Rapid Morph",
        "Razor Sharp",
        "Speed Sharpening"
    },
    ["Piercing Shots"] = {
        "Bludgeoner",
        "Charge Up",
        "Critical Draw",
        "Handicraft",
        "Horn Maestro",
        --"Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Rapid Morph",
        "Razor Sharp",
        "Speed Sharpening"
    },
    ["Poison Functionality"] = {
        "Artillery",
        "Bludgeoner",
        "Charge Up",
        "Critical Draw",
        "Guard",
        "Guard Up",
        "Handicraft",
        "Horn Maestro",
        "Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Offensive Guard",
        "Opening Shot",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Rapid Fire Up",
        "Rapid Morph",
        "Razor Sharp",
        "Speed Sharpening"
    },
    ["Power Prolonger"] = {
        "Ballistics",
        "Blast Functionality",
        "Charge Up",
        "Exhaust Functionality",
        "Horn Maestro",
        "Normal Shots",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Protective Polish"] = {
        "Ballistics",
        "Blast Functionality",
        "Exhaust Functionality",
        "Normal Shots",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Punishing Draw"] = {
        "Ballistics",
        "Blast Functionality",
        "Exhaust Functionality",
        "Normal Shots",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Rapid Fire Up"] = {
        --"Airborne",
        "Blast Functionality",
        "Bludgeoner",
        "Charge Master",
        "Charge Up",
        "Critical Draw",
        "Exhaust Functionality",
        "Guard",
        "Guard Up",
        "Handicraft",
        "Horn Maestro",
        "Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Offensive Guard",
        "Para Functionality",
        "Poison Functionality",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Razor Sharp",
        "Rapid Morph",
        "Sleep Functionality",
        "Speed Sharpening"
    },
    ["Rapid Morph"] = {
        "Ballistics",
        "Blast Functionality",
        "Charge Up",
        "Exhaust Functionality",
        "Horn Maestro",
        "Normal Shots",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Razor Sharp"] = {
        "Ballistics",
        "Blast Functionality",
        "Exhaust Functionality",
        "Normal Shots",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Sleep Functionality"] = {
        "Artillery",
        "Bludgeoner",
        "Charge Up",
        "Critical Draw",
        "Guard",
        "Guard Up",
        "Handicraft",
        "Horn Maestro",
        "Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Offensive Guard",
        "Opening Shot",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Rapid Fire Up",
        "Rapid Morph",
        "Razor Sharp",
        "Speed Sharpening"
    },
    --["Slugger"] = {},
    ["Special Ammo Boost"] = {
        "Bludgeoner",
        "Charge Up",
        "Critical Draw",
        "Handicraft",
        "Horn Maestro",
        --"Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Rapid Morph",
        "Razor Sharp",
        "Speed Sharpening"
    },
    ["Speed Sharpening"] = {
        "Ballistics",
        "Blast Functionality",
        "Exhaust Functionality",
        "Normal Shots",
        "Opening Shot",
        "Para Functionality",
        "Piercing Shots",
        "Poison Functionality",
        "Rapid Fire Up",
        "Sleep Functionality",
        "Special Ammo Boost",
        "Spread/Power Shots",
        "Tetrad Shot"
    },
    ["Spread/Power Shots"] = {
        "Bludgeoner",
        "Charge Up",
        "Critical Draw",
        "Handicraft",
        "Horn Maestro",
        --"Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Rapid Morph",
        "Razor Sharp",
        "Speed Sharpening"
    },
    --["Stamina Thief"] = {},
    ["Tetrad Shot"] = {
        "Bludgeoner",
        "Charge Up",
        "Critical Draw",
        "Handicraft",
        "Horn Maestro",
        --"Load Shells",
        "Master's Touch",
        "Mind's Eye",
        "Power Prolonger",
        "Protective Polish",
        "Punishing Draw",
        "Rapid Morph",
        "Razor Sharp",
        "Speed Sharpening"
    },
}

return SkillsIncompatibility